#%RAML 1.0 ResourceType
description: Entity representing <<resourcePathName|!singularize>>
get:
  description: Returns a <<resourcePathName|!singularize>>.
  responses:
    200:
      body:
        application/json:
          type: <<provider>>.inspect_<<resourcePathName|!singularize>>
    404:
      body:
        application/json: |
          {"message": "<<resourcePathName|!singularize>> not found" }
