#%RAML 1.0 ResourceType
description: A collection of <<resourcePathName>>
get:
  description: Returns a list of <<resourcePathName|!pluralize>>.
  responses:
    200:
      body:
        application/json:
          type: <<provider>>.<<resourcePathName|!pluralize>>
post:
  description: Create a new <<resourcePathName|!singularize>>.
  body:
    application/json:
      type: <<provider>>.<<resourcePathName|!singularize>>
  responses:
    201:
    404:
