#%RAML 1.0 ResourceType
description: A collection of <<resourcePathName>>
get:
  description: Returns a list of <<resourcePathName|!pluralize>>.
  responses:
    200:
      body:
        application/json:
          type: <<provider>>.<<resourcePathName|!pluralize>>
