---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contiv-netplugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contiv-netplugin
subjects:
- kind: ServiceAccount
  name: contiv-netplugin
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contiv-netplugin
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - endpoints
      - nodes
      - namespaces
      - networkpolicies
      - pods
      - services
    verbs:
      - watch
      - list
      - update
      - get

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: contiv-netplugin
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: contiv-netmaster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contiv-netmaster
subjects:
- kind: ServiceAccount
  name: contiv-netmaster
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: contiv-netmaster
rules:
  - apiGroups:
    - ""
    - extensions
    resources:
      - pods
      - nodes
      - namespaces
      - networkpolicies
    verbs:
      - get
      - watch
      - list
      - update

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: contiv-netmaster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"

---

# This ConfigMap is used to configure a self-hosted Contiv installation.
# It can be used with an external cluster store(etcd or consul) or used
# with the etcd instance being installed as contiv-etcd
kind: ConfigMap
apiVersion: v1
metadata:
  name: contiv-config
  namespace: kube-system
data:
  contiv_mode: kubernetes
  contiv_fwdmode: routing
  contiv_netmode: vxlan
  contiv_etcd: "http://10.96.232.136:6666"
  contiv_cni_config: |-
    {
      "cniVersion": "0.3.1",
      "name": "contiv-net",
      "type": "contivk8s"
    }
  contiv_k8s_config: |-
    {
       "K8S_API_SERVER": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
       "K8S_CA": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
       "K8S_KEY": "",
       "K8S_CERT": "",
       "K8S_TOKEN": "",
       "SVC_SUBNET": "10.96.0.0/12"
    }

---

# This manifest installs contiv-netplugin container, as well
# as the Contiv CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: contiv-netplugin
  namespace: kube-system
  labels:
    k8s-app: contiv-netplugin
spec:
  selector:
    matchLabels:
      k8s-app: contiv-netplugin
  template:
    metadata:
      labels:
        k8s-app: contiv-netplugin
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: contiv-netplugin
      initContainers:
        - name: contiv-netplugin-init
          image: contiv/netplugin-init:latest
          env:
            - name: CONTIV_ROLE
              value: netplugin
            - name: CONTIV_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_mode
            - name: CONTIV_K8S_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_k8s_config
            - name: CONTIV_CNI_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_cni_config
          volumeMounts:
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
            - mountPath: /etc/cni/net.d/
              name: etc-cni-dir
              readOnly: false
        - name: contiv-cni
          image: contiv/netplugin:latest
          command: ["cp", "/contiv/bin/contivk8s", "/opt/cni/bin/contivk8s"]
          volumeMounts:
            - mountPath: /opt/cni/bin
              name: cni-bin-dir
              readOnly: false
      containers:
        - name: contiv-netplugin
          image: contiv/netplugin:latest
          env:
            - name: CONTIV_ROLE
              value: netplugin
            - name: CONTIV_NETPLUGIN_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_mode
            - name: CONTIV_NETPLUGIN_VTEP_IP
              valueFrom:
                 fieldRef:
                    fieldPath: status.podIP
            - name: CONTIV_NETPLUGIN_ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_etcd
            - name: CONTIV_NETPLUGIN_FORWARD_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_fwdmode
            - name: CONTIV_NETPLUGIN_NET_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_netmode
          resources:
            requests:
              cpu: 250m
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run
              name: var-run
              readOnly: false
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
        - name: var-contiv
          hostPath:
            path: /var/contiv
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: etc-cni-dir
          hostPath:
            path: /etc/cni/net.d/

---

# This manifest deploys the Contiv API Server on Kubernetes.
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: contiv-netmaster
  namespace: kube-system
  labels:
    k8s-app: contiv-netmaster
spec:
  # The netmaster should have 1, 3, 5 nodes of which one is active at any given time.
  # More nodes are desired in a production environment for HA.
  replicas: 1
  template:
    metadata:
      name: contiv-netmaster
      namespace: kube-system
      labels:
        k8s-app: contiv-netmaster
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      # The netmaster must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      serviceAccountName: contiv-netmaster
      initContainers:
        - name: contiv-netplugin-init
          image: contiv/netplugin-init:latest
          env:
            - name: CONTIV_ROLE
              value: netmaster
            - name: CONTIV_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_mode
            - name: CONTIV_K8S_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_k8s_config
            - name: CONTIV_CNI_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_cni_config
          volumeMounts:
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
        - name: contiv-netctl
          image: contiv/netplugin:latest
          command: ["cp", "/contiv/bin/netctl", "/usr/local/sbin/netctl"]
          volumeMounts:
            - mountPath: /usr/local/sbin/
              name: usr-local-sbin
              readOnly: false
      containers:
        - name: contiv-netmaster
          image: contiv/netplugin:latest
          env:
            - name: CONTIV_ROLE
              value: netmaster
            - name: CONTIV_NETMASTER_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_mode
            - name: CONTIV_NETMASTER_ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_etcd
            - name: CONTIV_NETMASTER_FORWARD_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_fwdmode
            - name: CONTIV_NETMASTER_NET_MODE
              valueFrom:
                configMapKeyRef:
                  name: contiv-config
                  key: contiv_netmode
          volumeMounts:
            - mountPath: /var/contiv
              name: var-contiv
              readOnly: false
      volumes:
        # Used by contiv-netmaster
        - name: var-contiv
          hostPath:
            path: /var/contiv
        - name: usr-local-sbin
          hostPath:
            path: /usr/local/sbin/

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contiv-etcd
  namespace: kube-system
  labels:
    k8s-app: contiv-etcd
spec:
  template:
    metadata:
      labels:
        k8s-app: contiv-etcd
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      # Only run this pod on the master.
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
        - name: contiv-etcd
          image: quay.io/coreos/etcd:v3.2.4
          command: ["/bin/sh","-c"]
          args:
            - ETCD_ADVERTISE_CLIENT_URLS=http://$CONTIV_ETCD_IP:6666 /usr/local/bin/etcd
          env:
            - name: CONTIV_ETCD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ETCD_NAME
              value: contiv-etcd
            - name: ETCD_DATA_DIR
              value: /var/lib/etcd/contiv-data
            - name: ETCD_LISTEN_CLIENT_URLS
              value: http://0.0.0.0:6666
            - name: ETCD_LISTEN_PEER_URLS
              value: http://0.0.0.0:6667
          volumeMounts:
            - name: var-etcd
              mountPath: /var/etcd
      volumes:
        - name: var-etcd
          hostPath:
            path: /var/etcd

---

apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: contiv-etcd
  name: contiv-etcd
  namespace: kube-system
spec:
  # Select the contiv-etcd pod running on the master.
  selector:
    k8s-app: contiv-etcd
  # This ClusterIP needs to be known in advance, since we cannot rely
  # on DNS to get access to etcd.
  clusterIP: 10.96.232.136
  ports:
    - port: 6666

---
# This manifest deploys the contiv-ovs pod.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: contiv-ovs
  namespace: kube-system
  labels:
    k8s-app: contiv-ovs
spec:
  selector:
    matchLabels:
      k8s-app: contiv-ovs
  template:
    metadata:
      labels:
        k8s-app: contiv-ovs
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        # Runs ovs containers on each Kubernetes node.
        - name: contiv-ovsdb-server
          image: contiv/ovs:latest
          command: ["/scripts/start-ovsdb-server.sh"]
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: /etc/openvswitch
              name: etc-openvswitch
              readOnly: false
            - mountPath: /var/run
              name: var-run
              readOnly: false
        - name: contiv-ovs-vswitchd
          image: contiv/ovs:latest
          command: ["/scripts/start-ovs-vswitchd.sh"]
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/openvswitch
              name: etc-openvswitch
              readOnly: false
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run
              name: var-run
              readOnly: false
      volumes:
        # Used by contiv-ovs
        - name: etc-openvswitch
          hostPath:
            path: /etc/openvswitch
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run
          hostPath:
            path: /var/run
