#!/bin/bash

IS_NETMASTER=1
NETMASTER_IP="172.28.11.253"
VTEP_IP="172.28.11.254"
VLAN_IF="ens33"
CONTIV_FWD_MODE="routing"

if [ $IS_NETMASTER == 1 ]
then
   /contiv/bin/netmaster 2>&1 /var/log/contiv/netmaster.log
fi

echo "$NETMASTER_IP  netmaster" > /etc/hosts
echo "0.0.0.0 localhost" >> /etc/hosts

export no_proxy="0.0.0.0, $NETMASTER_IP" 

if [ not $CONTIV_MODE == "routing" ] 
then
   CONTIV_MODE="bridged"
fi

/contiv/bin/netplugin -vtep-ip $VTEP_IP -vlan-if $VLAN_IF -fwd-mode $CONTIV_FWD_MODE 2>&1 /var/log/contiv/netplugin.log

