#!/bin/bash

num_nodes=1
if [ -n "$CONTIV_NODES" ];
then
    num_nodes=$CONTIV_NODES
fi
echo $num_nodes

for i in `seq 1 $num_nodes`; 
do
    host="netplugin-node$i"
    echo "Cleaning $host"
    sudo docker exec $host service docker stop
    sudo ip link delete $i-ext
    sudo docker rm -f -v $host
done
