#!/bin/bash

#performs basic dev and build environment checks

echo "Checking Go version..."
ver=$(go version | awk '{print $3}')
if [[ $ver < "go1.4" ]]; then
    echo "Go version check failed. Expected 1.4 but found $ver"
    exit 1
fi

echo "Checking gofmt..."
fmtRes=$(gofmt -l ./)
if [ -n "${fmtRes}" ]; then
    echo -e "gofmt checking failed:\n${fmtRes}"
    exit 1
fi

echo "All checks passed!!"
