#!/bin/bash

#performs basic dev and build environment checks

USAGE="Usage: $0 <build packages>"

if [ $# -ne 1 ]; then
    echo $USAGE
    exit 1
fi

BUILD_PKGS=$1

echo "+++ Checking Go version..."
ver=$(go version | awk '{print $3}')
minVer="go1.4"
if [[ ${ver} < ${minVer} ]]; then
    echo "!!! Go version check failed. Expected >=${minVer} but found ${ver}"
    exit 1
fi

echo "+++ Checking gofmt..."
fmtRes=$(gofmt -l $BUILD_PKGS)
if [ -n "${fmtRes}" ]; then
    echo -e "!!! gofmt checking failed:\n${fmtRes}"
    exit 1
fi

echo "+++ golint tree..."
for i in $(find . -maxdepth 1 -type d -name '*' | grep -vE '/\..*$')
do
  output="${output}$(golint ${i})" # golint has no exit codes
done

if [ -n "${output}" ]
then
  echo -e "!!! golint checking failed: "
  echo -n "${output}"
  exit 1
fi

echo "+++ go vet tree..."
for i in ${BUILD_PKGS}
do
  if ! go vet "${i}"
  then
    echo "!!! go vet failed for the following package: ${i}"
    exit 1
  fi
done

echo "+++ All checks passed!!"
exit 0
