#!/bin/bash

go get github.com/tools/godep
go get github.com/aktau/github-release
go get github.com/contiv/modelgen

if ! go get -u github.com/golang/lint/golint
then
  echo "!!! Could not install golint"
  exit 1
fi

if ! go get -u github.com/client9/misspell/cmd/misspell
then
  echo "!!! Could not install misspell"
  exit 1
fi
